apiVersion: v1
kind: Service
metadata:
  name: flaskapi
  labels:
    app: flaskapi
  namespace: mymongo
spec:
  type: ClusterIP
  selector:
    app: flaskapi
  ports:
  - name: flask
    port: 5000
    protocol: TCP
    targetPort: 5000
